import { useState, type FormEvent } from 'react';
import { ArrowRight, BookOpen, BriefcaseBusiness, CalendarDays, ChevronRight, FileText, Pencil, Plus, Search, Sparkles, Trash2, Upload } from 'lucide-react';
import { api, date, label, patch, post, remove } from './api';
import { errorMessage, useApp } from './context';
import type { Job, Round } from './types';
import { Badge, Button, Empty, Field, Modal, SectionTitle } from './ui';

export default function Jobs() {
  const {data,selectedJob,setSelectedJob,navigate,refresh,notify}=useApp();
  const [search,setSearch]=useState('');
  const [edit,setEdit]=useState<Job|'new'|null>(null);
  const [round,setRound]=useState<Round|'new'|null>(null);
  const [busy,setBusy]=useState('');
  const job=data.jobs.find(j=>j.id===selectedJob) || data.jobs[0];
  const filtered=data.jobs.filter(j=>`${j.title} ${j.company}`.toLowerCase().includes(search.toLowerCase()));
  const run=async(action:string)=>{if(!job)return;setBusy(action);try{await post(`/jobs/${job.id}/${action}`);notify(action==='extract'?'Reading the job description. Watch background activity for progress.':'Your preparation plan is being created.');await refresh();}catch(e){notify(errorMessage(e),true);}finally{setBusy('');}};
  const deleteJob=async()=>{if(!job||!confirm(`Delete “${job.title}” and its associated preparation, rounds, sessions, and recordings? This cannot be undone.`))return;try{await remove(`/jobs/${job.id}`);setSelectedJob('');await refresh();notify('Opportunity deleted.');}catch(e){notify(errorMessage(e),true);}};
  const deleteRound=async(item:Round)=>{if(!confirm(`Delete the round “${item.title}”?`))return;try{await remove(`/rounds/${item.id}`);await refresh();}catch(e){notify(errorMessage(e),true);}};
  return <><div className="toolbar"><div className="search-input"><Search size={17}/><input placeholder="Search opportunities…" aria-label="Search opportunities" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button onClick={()=>setEdit('new')}><Plus size={16}/>Add opportunity</Button></div>
    {!data.jobs.length?<div className="card"><Empty icon={BriefcaseBusiness} title="Every great interview starts here" text="Paste a job description, add your experience, and get a preparation plan built around the position you want."><Button onClick={()=>setEdit('new')}><Plus size={16}/>Add your first opportunity</Button></Empty></div>:<div className="jobs-layout"><div className="job-list">{filtered.map(item=><button className={`card job-list-item ${job?.id===item.id?'selected':''}`} key={item.id} onClick={()=>setSelectedJob(item.id)}><div className="row-between"><span className="company-avatar">{(item.company||item.title).slice(0,1).toUpperCase()}</span><Badge color={item.status==='archived'?'neutral':'amber'}>{label(item.status)}</Badge></div><h3>{item.title}</h3><p>{item.company || 'Personal preparation'}</p><div className="job-list-footer"><span>{label(item.seniority)}</span><ChevronRight size={15}/></div></button>)}{!filtered.length&&<p className="muted">No matching opportunities.</p>}</div>
    {job&&<div className="job-details"><section className="card job-profile"><div className="row-between"><Badge color="amber">{label(job.seniority)} · {label(job.status)}</Badge><div className="inline-actions"><button className="icon-button" aria-label="Edit opportunity" onClick={()=>setEdit(job)}><Pencil size={17}/></button><button className="icon-button danger-text" aria-label="Delete opportunity" onClick={()=>void deleteJob()}><Trash2 size={17}/></button></div></div><h2>{job.title}</h2><p className="company-name"><BriefcaseBusiness size={16}/>{job.company || 'Personal preparation'}</p><div className="job-actions"><Button onClick={()=>{setSelectedJob(job.id);navigate('Preparation');}}><BookOpen size={16}/>Preparation plan<ArrowRight size={15}/></Button><Button variant="secondary" onClick={()=>{setSelectedJob(job.id);navigate('Practice');}}>Practice this role</Button></div><details className="description-details"><summary><FileText size={16}/>Job description<ChevronRight size={15}/></summary><p className="preserve-text">{job.description}</p></details>{job.resume_text&&<details className="description-details"><summary><FileText size={16}/>Your experience<ChevronRight size={15}/></summary><p className="preserve-text">{job.resume_text}</p></details>}</section>
    <section className="card"><SectionTitle title="What this role needs" subtitle="Review these requirements before creating your plan." action={<Button variant="ghost" busy={busy==='extract'} onClick={()=>void run('extract')}><Sparkles size={15}/>{job.requirements.length?'Re-extract':'Extract requirements'}</Button>}/>{job.requirements.length?<><ul className="requirement-list">{job.requirements.map((r,i)=><li key={i}><span className="requirement-number">{String(i+1).padStart(2,'0')}</span>{r}</li>)}</ul><button className="text-link" onClick={()=>setEdit(job)}><Pencil size={14}/>Review and edit requirements</button></>:<p className="muted">Helios can identify the skills, responsibilities, and experience to prepare for. Connect your model in Settings, then extract requirements.</p>}</section>
    <section className="card"><SectionTitle title="Interview rounds" subtitle="Keep the schedule and the outcome in one place." action={<Button variant="secondary" onClick={()=>setRound('new')}><Plus size={15}/>Add round</Button>}/>{data.rounds.filter(r=>r.job_id===job.id).length?<div className="round-list">{data.rounds.filter(r=>r.job_id===job.id).map(item=><article className="round-card" key={item.id}><div className="row-between"><div><h3>{item.title}</h3><p>{label(item.kind)} · {date(item.scheduled_at,true)}</p></div><Badge color={item.status==='completed'?'green':'amber'}>{label(item.status)}</Badge></div>{item.outcome&&<p><strong>Outcome:</strong> {item.outcome}</p>}{item.notes&&<p className="preserve-text">{item.notes}</p>}<div className="inline-actions"><button className="text-link" onClick={()=>setRound(item)}><Pencil size={14}/>Edit round</button><button className="icon-button danger-text" aria-label={`Delete ${item.title}`} onClick={()=>void deleteRound(item)}><Trash2 size={14}/></button></div></article>)}</div>:<Empty icon={CalendarDays} compact title="Your next conversation belongs here" text="Track screening calls, role-specific rounds, and final conversations."/>}</section></div>}</div>}
    {edit&&<JobEditor job={edit==='new'?undefined:edit} onClose={()=>setEdit(null)}/>}
    {round&&job&&<RoundEditor jobId={job.id} round={round==='new'?undefined:round} onClose={()=>setRound(null)}/>}
  </>;
}

function JobEditor({job,onClose}:{job?:Job;onClose:()=>void}) {
  const {refresh,notify,setSelectedJob}=useApp();
  const [form,setForm]=useState({title:job?.title||'',company:job?.company||'',description:job?.description||'',resume_text:job?.resume_text||'',seniority:job?.seniority||'mid',status:job?.status||'active',requirements:job?.requirements.join('\n')||''});
  const [busy,setBusy]=useState(false),[extracting,setExtracting]=useState(false);
  const field=(key:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm({...form,[key]:e.target.value});
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const payload={...form,requirements:form.requirements.split('\n').map(s=>s.trim()).filter(Boolean)};const saved=job?await patch<Job>(`/jobs/${job.id}`,payload):await post<Job>('/jobs',payload);setSelectedJob(saved.id);await refresh();notify(job?'Opportunity updated.':'Opportunity added. Extract and review the requirements to get started.');onClose();}catch(error){notify(errorMessage(error),true);}finally{setBusy(false);}};
  const upload=async(file?:File)=>{if(!file)return;setExtracting(true);try{const body=new FormData();body.append('file',file);const result=await api<{text:string}>('/documents/extract',{method:'POST',body});setForm(current=>({...current,resume_text:result.text}));notify('Resume text extracted. Review it below before saving.');}catch(error){notify(errorMessage(error),true);}finally{setExtracting(false);}};
  return <Modal title={job?'Edit opportunity':'Your next opportunity'} subtitle="Tell Helios what you’re aiming for. The more context, the better the preparation." wide onClose={onClose}><form onSubmit={e=>void submit(e)} className="form-stack"><div className="form-row"><Field label="Position"><input required autoFocus placeholder="e.g. Senior Product Designer" value={form.title} onChange={field('title')}/></Field><Field label="Company"><input placeholder="e.g. Acme" value={form.company} onChange={field('company')}/></Field></div><div className="form-row"><Field label="Seniority"><select value={form.seniority} onChange={field('seniority')}>{['entry','junior','mid','senior','lead','executive'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={field('status')}>{['active','applied','interviewing','offer','rejected','archived'].map(s=><option key={s}>{s}</option>)}</select></Field></div><Field label="Job description"><textarea required rows={7} placeholder="Paste the full job description here…" value={form.description} onChange={field('description')}/></Field><div className="row-between"><h3>Your experience <small className="muted">optional</small></h3><label className="button secondary file-button"><Upload size={15}/>{extracting?'Extracting…':'Import resume'}<input type="file" accept=".pdf,.docx,.txt,.md" disabled={extracting} onChange={e=>void upload(e.target.files?.[0])}/></label></div><Field label="Resume text" hint="PDF, DOCX, or text. Scanned PDFs need OCR before import."><textarea rows={5} placeholder="Paste or import your experience, projects, and strengths…" value={form.resume_text} onChange={field('resume_text')}/></Field>{job&&<Field label="Reviewed requirements" hint="One requirement per line. Edit Helios’s extracted list before generating a plan."><textarea rows={6} value={form.requirements} onChange={field('requirements')}/></Field>}<div className="modal-footer"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" busy={busy} disabled={extracting}>{job?'Save changes':'Add opportunity'}<ArrowRight size={15}/></Button></div></form></Modal>;
}

function RoundEditor({round,jobId,onClose}:{round?:Round;jobId:string;onClose:()=>void}) {
  const {refresh,notify}=useApp();
  const localDate=round?.scheduled_at?new Date(new Date(round.scheduled_at).getTime()-new Date(round.scheduled_at).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
  const [form,setForm]=useState({title:round?.title||'',kind:round?.kind||'screening',scheduled_at:localDate,status:round?.status||'scheduled',outcome:round?.outcome||'',notes:round?.notes||''});
  const [busy,setBusy]=useState(false);
  const field=(key:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm({...form,[key]:e.target.value});
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const payload={...form,job_id:jobId,scheduled_at:form.scheduled_at?new Date(form.scheduled_at).toISOString():''};if(round)await patch(`/rounds/${round.id}`,payload);else await post('/rounds',payload);await refresh();onClose();}catch(error){notify(errorMessage(error),true);}finally{setBusy(false);}};
  return <Modal title={round?'Edit interview round':'Add an interview round'} onClose={onClose}><form className="form-stack" onSubmit={e=>void submit(e)}><Field label="Round title"><input required autoFocus value={form.title} placeholder="e.g. Technical conversation with the team" onChange={field('title')}/></Field><div className="form-row"><Field label="Round type"><select value={form.kind} onChange={field('kind')}>{['screening','behavioral','role_specific','leadership'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></Field><Field label="Date and time"><input type="datetime-local" value={form.scheduled_at} onChange={field('scheduled_at')}/></Field></div><Field label="Status"><select value={form.status} onChange={field('status')}>{['scheduled','completed','cancelled'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Outcome"><input value={form.outcome} onChange={field('outcome')} placeholder="e.g. Moving to the next round"/></Field><Field label="Notes"><textarea value={form.notes} rows={4} onChange={field('notes')}/></Field><div className="modal-footer"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" busy={busy}>Save round</Button></div></form></Modal>;
}
