import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, Check, LoaderCircle, RefreshCw, Sparkles } from 'lucide-react';
import { date, post } from './api';
import { errorMessage, useApp } from './context';
import { Badge, Button, Empty, PlanView } from './ui';

export default function Preparation(){
  const {data,selectedJob,setSelectedJob,navigate,refresh,notify}=useApp();
  const [busy,setBusy]=useState(false),[version,setVersion]=useState(''),[reviewed,setReviewed]=useState(false),[requestError,setRequestError]=useState('');
  const job=data.jobs.find(j=>j.id===selectedJob)||data.jobs[0];
  const plans=data.preparations.filter(p=>p.job_id===job?.id).sort((a,b)=>b.created_at.localeCompare(a.created_at));
  const plan=plans.find(p=>p.id===version)||plans[0];
  const tasks=data.tasks.filter(t=>t.kind==='preparation'&&t.target_id===job?.id).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));
  const activeTask=tasks.find(t=>['queued','running'].includes(t.status));
  const latestTask=activeTask||tasks[0];
  const failedTask=latestTask&&['failed','cancelled'].includes(latestTask.status)?latestTask:undefined;
  const progress=activeTask?Math.max(0,Math.min(100,activeTask.progress<=1?activeTask.progress*100:activeTask.progress)):0;
  useEffect(()=>{setReviewed(false);setRequestError('');},[job?.id,job?.requirements.join('\n')]);
  useEffect(()=>{setVersion('');},[job?.id,plans[0]?.id]);
  const generate=async(retry=false)=>{if(!job)return;setBusy(true);setRequestError('');try{await post(retry&&failedTask?`/tasks/${failedTask.id}/retry`:`/jobs/${job.id}/prepare`);setVersion('');await refresh();notify('Your learning path is being created. You can keep using Helios while it works.');}catch(e){setRequestError(errorMessage(e));notify(errorMessage(e),true);}finally{setBusy(false);}};
  if(!job)return <div className="card"><Empty icon={BookOpen} title="Preparation built around your next role" text="Add a job description first. Helios will connect the role’s requirements to your experience, then build a path from foundations to advanced practice."><Button onClick={()=>navigate('Jobs')}>Add an opportunity<ArrowRight size={16}/></Button></Empty></div>;
  return <><div className="toolbar"><div className="selector-wrap"><span className="eyebrow">PREPARING FOR</span><select value={job.id} aria-label="Select opportunity" onChange={e=>{setSelectedJob(e.target.value);setVersion('');setReviewed(false);}}>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.title}{j.company?` · ${j.company}`:''}</option>)}</select></div>{plan&&<Button variant="secondary" onClick={()=>navigate('Practice')}>Put it into practice<ArrowRight size={15}/></Button>}</div>
    <div className="card prep-context"><div><Badge color="amber">PERSONAL LEARNING PATH</Badge><h2>{job.title}</h2><p>{job.company||'Your next opportunity'} · {job.seniority} level</p></div><div>{plan?<><small className="muted">Created {date(plan.created_at)}</small><select aria-label="Preparation version" value={plan.id} onChange={e=>setVersion(e.target.value)}>{plans.map((p,i)=><option key={p.id} value={p.id}>{i===0?'Latest plan':`Earlier plan ${plans.length-i}`} · {date(p.created_at)}</option>)}</select></>:<span className="prep-symbol"><BookOpen size={30}/></span>}</div></div>
    {activeTask&&<section className="card" role="status" aria-live="polite"><div className="row-between"><h3><LoaderCircle size={17} className="spin"/> {activeTask.status==='queued'?'Preparation is queued':'Creating your preparation'}</h3><Badge color="amber">{Math.round(progress)}%</Badge></div><p className="muted">{activeTask.message||'Helios is building a learning path for this opportunity.'}</p><div className="score-track" role="progressbar" aria-label="Preparation progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)}><span style={{width:`${progress}%`}}/></div><p className="field-hint">You can leave this page. Your plan will appear here when processing finishes.</p></section>}
    {!activeTask&&(failedTask||requestError)&&<section className="notice error-notice" role="alert"><h3>{failedTask?.status==='cancelled'?'Preparation was cancelled':'Preparation could not be created'}</h3><p>{requestError||failedTask?.error||failedTask?.message||'The model did not return a usable plan. Check the connection and try again.'}</p><p>{plan?'Your earlier preparation plans are still available below.':'Your job description, experience, and requirements are saved.'}</p><div className="inline-actions"><Button variant="secondary" busy={busy} disabled={!job.requirements.length} onClick={()=>void generate(!!failedTask)}><RefreshCw size={15}/>{failedTask?'Retry preparation':'Try creating again'}</Button><button className="text-link" onClick={()=>navigate('Settings')}>Check model settings<ArrowRight size={14}/></button></div></section>}
    {!plan&&<div className="card preparation-start"><div className="section-heading"><div><h2>First, make the direction yours.</h2><p>Review the requirements so Helios focuses on the right things.</p></div><button className="text-link" onClick={()=>navigate('Jobs')}>Edit requirements<ArrowRight size={14}/></button></div>{job.requirements.length?<ul className="requirement-list">{job.requirements.map((r,i)=><li key={i}><Check size={16}/>{r}</li>)}</ul>:<p className="notice">Extract or enter the role requirements in Jobs before generating your plan.</p>}<label className="checkbox-label"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I’ve reviewed these requirements and I’m ready to prepare.</label><Button busy={busy||!!activeTask} disabled={!reviewed||!job.requirements.length} onClick={()=>void generate()}><Sparkles size={16}/>{activeTask?'Creating your preparation…':'Create my preparation plan'}</Button></div>}
    {plan&&<><PlanView plan={plan.plan}/><div className="regenerate-row"><p>Changed your experience or requirements? Create a fresh plan. Previous plans stay available.</p><Button variant="secondary" busy={busy||!!activeTask} onClick={()=>void generate()}><Sparkles size={15}/>Create a new version</Button></div></>}
  </>;
}
