import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Download, FileAudio, Headphones, Pencil, Play, Search, Sparkles, Trash2, Upload, Users } from 'lucide-react';
import { api, date, label, latestAssessments, patch, post, remove, time } from './api';
import { errorMessage, useApp } from './context';
import type { Segment, Session, SessionDetail } from './types';
import { Badge, Button, Empty, Field, Modal, ReportView, SectionTitle } from './ui';

export default function Recordings(){
  const {data,selectedSession,setSelectedSession,navigate,refresh,notify}=useApp();
  const [search,setSearch]=useState(''),[importing,setImporting]=useState(false);
  const selected=data.sessions.find(s=>s.id===selectedSession);
  const currentReviews=latestAssessments(data.assessments);
  const sessions=data.sessions.filter(s=>`${s.title} ${s.kind} ${data.jobs.find(j=>j.id===s.job_id)?.company||''}`.toLowerCase().includes(search.toLowerCase()));
  const erase=async(session:Session)=>{if(!confirm(`Delete “${session.title}”, its recording, transcript, and all reviews? This cannot be undone.`))return;try{await remove(`/sessions/${session.id}`);if(selectedSession===session.id)setSelectedSession('');await refresh();notify('Session and recording deleted.');}catch(e){notify(errorMessage(e),true);}};
  return <>{selected?<SessionReview session={selected} onBack={()=>setSelectedSession('')} onDelete={()=>void erase(selected)}/>:<><div className="toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search recordings" placeholder="Search your conversations…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button onClick={()=>setImporting(true)}><Upload size={16}/>Import recording</Button></div>{!data.sessions.length?<div className="card"><Empty icon={Headphones} title="A library of lessons, in your own voice." text="Your practice recordings will appear here. You can also import a recorded interview for transcription and feedback."><Button variant="secondary" onClick={()=>navigate('Practice')}>Start your first practice<ArrowRight size={15}/></Button></Empty></div>:<div className="recordings-grid">{sessions.map(session=>{const report=currentReviews.find(a=>a.session_id===session.id);return <article key={session.id} className="card recording-card"><div className="row-between"><span className="session-icon"><FileAudio size={21}/></span><Badge color={['completed','reviewed'].includes(session.status)?'green':session.status==='failed'?'red':'neutral'}>{label(session.status)}</Badge></div><h3>{session.title}</h3><p>{data.jobs.find(j=>j.id===session.job_id)?.company||label(session.kind)}</p><div className="recording-wave" aria-hidden="true">{Array.from({length:38},(_,i)=><i key={i} style={{height:`${6+((i*13+19)%29)}px`}}/>)}</div><div className="recording-meta"><span>{date(session.created_at)}</span><span>{time(session.duration_seconds)}</span><span>{session.source==='upload'?'Imported':'Practice'}</span></div><div className="recording-footer"><Button variant="secondary" onClick={()=>setSelectedSession(session.id)}><Play size={14}/>Open session</Button>{report?.report.overall_score!=null&&<span className="mini-score">{report.report.overall_score.toFixed(1)}<small>/ 5</small></span>}<button className="icon-button danger-text" aria-label={`Delete ${session.title}`} onClick={()=>void erase(session)}><Trash2 size={15}/></button></div></article>;})}{!sessions.length&&<p className="muted">No recordings match your search.</p>}</div>}</>}{importing&&<ImportModal onClose={()=>setImporting(false)}/>}</>;
}

function SessionReview({session,onBack,onDelete}:{session:Session;onBack:()=>void;onDelete:()=>void}){
  const {data,notify,refresh}=useApp();
  const [detail,setDetail]=useState<SessionDetail|null>(null),[tab,setTab]=useState<'review'|'transcript'>('review'),[search,setSearch]=useState(''),[edit,setEdit]=useState<Segment|null>(null),[version,setVersion]=useState(''),[busy,setBusy]=useState(false),[mapping,setMapping]=useState<Record<string,string>>({});
  const player=useRef<HTMLAudioElement>(null);
  const fetchDetail=async()=>{try{setDetail(await api<SessionDetail>(`/sessions/${session.id}`));}catch(e){notify(errorMessage(e),true);}};
  useEffect(()=>{void fetchDetail();},[session.id,data.assessments.length,data.tasks.filter(t=>['running','queued'].includes(t.status)).length]);
  const segments=detail?.segments||[];
  const speakers=[...new Set(segments.map(s=>s.speaker).filter((s):s is string=>!!s))];
  const reports=[...(detail?.assessments||[])].sort((a,b)=>b.created_at.localeCompare(a.created_at));
  const assessment=reports.find(a=>a.id===version)||reports[0];
  const seek=(seconds:number)=>{if(player.current){player.current.currentTime=seconds;void player.current.play().catch(e=>notify(errorMessage(e),true));}};
  const assess=async()=>{setBusy(true);try{await post(`/sessions/${session.id}/assess`);await refresh();notify('Your session review is being created. Previous reviews stay available.');}catch(e){notify(errorMessage(e),true);}finally{setBusy(false);}};
  const saveSpeakers=async()=>{setBusy(true);try{const full=Object.fromEntries(speakers.map(s=>[s,mapping[s]||segments.find(segment=>segment.speaker===s)?.role||'unknown']));await post(`/sessions/${session.id}/speakers`,{mapping:full});await fetchDetail();await refresh();notify('Speakers saved. Create a fresh review to use your corrections.');}catch(e){notify(errorMessage(e),true);}finally{setBusy(false);}};
  const hasCandidate=segments.some(s=>s.role==='candidate'&&s.text.trim());
  const activeTask=data.tasks.find(t=>t.target_id===session.id&&['running','queued'].includes(t.status));
  return <><div className="toolbar"><button className="text-link" onClick={onBack}><ArrowLeft size={16}/>All recordings</button><div className="inline-actions">{session.recording_url&&<a className="button secondary" href={session.recording_url} download><Download size={15}/>Download audio</a>}<button className="icon-button danger-text" aria-label="Delete this session" onClick={onDelete}><Trash2 size={17}/></button></div></div><div className="card recording-player"><div className="row-between"><Badge color="amber">{label(session.kind)} · {label(session.mode)}</Badge><span className="muted">{date(session.created_at,true)}</span></div><h2>{session.title}</h2><p>{data.jobs.find(j=>j.id===session.job_id)?.company||'Personal practice'} · {time(session.duration_seconds)}</p>{session.recording_url?<audio ref={player} controls preload="metadata" src={session.recording_url}>Your browser does not support audio playback.</audio>:<div className="notice">{session.source==='practice'?'No audio is available for this session. Typed conversations keep their transcript.':'The recording is still being processed. Check background activity for progress.'}</div>}</div>
    {activeTask&&<div className="notice"><strong>{label(activeTask.kind)}</strong> · {activeTask.message}</div>}
    {session.source==='upload'&&!!speakers.length&&<details className="card speaker-mapping" open={!hasCandidate}><summary><Users size={18}/><strong>Identify who’s speaking</strong><span className="muted">Select yourself before requesting a review.</span></summary><div className="speaker-fields">{speakers.map(speaker=><Field key={speaker} label={speaker} hint={segments.find(s=>s.speaker===speaker)?.text.slice(0,100)}><select value={mapping[speaker]||segments.find(s=>s.speaker===speaker)?.role||'unknown'} onChange={e=>setMapping({...mapping,[speaker]:e.target.value})}><option value="unknown">Not identified</option><option value="candidate">Me · candidate</option><option value="interviewer">Interviewer</option><option value="other">Other participant</option></select></Field>)}</div><Button variant="secondary" busy={busy} onClick={()=>void saveSpeakers()}>Save speaker labels</Button></details>}
    {session.source==='upload'&&segments.length>0&&!speakers.length&&!hasCandidate&&<div className="notice">Speaker separation was unavailable. Open the transcript and mark your answer segments as “Candidate” before requesting feedback.</div>}
    {session.source==='upload'&&segments.length>0&&!speakers.length&&hasCandidate&&!detail?.session.speakers_confirmed&&<div className="notice"><p>You have labeled your answers manually. Confirm these labels before requesting a review.</p><Button variant="secondary" busy={busy} onClick={()=>void saveSpeakers()}>Confirm my answers</Button></div>}
    <div className="tabs-row"><div className="tabs"><button className={tab==='review'?'active':''} onClick={()=>setTab('review')}>Session review</button><button className={tab==='transcript'?'active':''} onClick={()=>setTab('transcript')}>Transcript <span>{segments.length}</span></button></div><Button variant="secondary" busy={busy||!!activeTask} disabled={!hasCandidate} onClick={()=>void assess()}><Sparkles size={15}/>{assessment?'Create fresh review':'Analyze session'}</Button></div>
    {tab==='review'?(assessment?<><div className="review-version"><span className="muted">Review history</span><select value={assessment.id} aria-label="Select review version" onChange={e=>setVersion(e.target.value)}>{reports.map((r,i)=><option key={r.id} value={r.id}>{i===0?'Latest review':`Earlier review ${reports.length-i}`} · {date(r.created_at,true)}</option>)}</select></div>{assessment.stale&&<div className="notice">This review uses an earlier transcript or speaker assignment. Create a fresh review to include your corrections.</div>}<ReportView report={assessment.report} onSeek={session.recording_url?seek:undefined}/></>:<div className="card"><Empty icon={Sparkles} title={activeTask?'Your review is on its way.':'Turn the conversation into a next step.'} text={hasCandidate?'Analyze this transcript to see evidence-linked feedback, stronger answer examples, and focused practice drills.':'A review needs your answers. Once transcription finishes, identify your speaker or label candidate segments in the transcript.'}/></div>):<section className="card transcript-panel"><SectionTitle title="The conversation" subtitle="Correct transcription or speaker labels, then create a fresh review. Previous reviews remain unchanged."/><div className="search-input"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search transcript…" aria-label="Search transcript"/></div>{segments.filter(s=>s.text.toLowerCase().includes(search.toLowerCase())).map(segment=><article className="transcript-segment" key={segment.id}><button className="timestamp" disabled={!session.recording_url} onClick={()=>seek(segment.start)}><Play size={12}/>{time(segment.start)}</button><div><div className="row-between"><span className={`speaker-label ${segment.role}`}>{segment.role==='candidate'?'You':label(segment.role)}{segment.speaker?` · ${segment.speaker}`:''}</span><button className="icon-button" aria-label="Edit transcript segment" onClick={()=>setEdit(segment)}><Pencil size={14}/></button></div><p>{segment.text}</p></div></article>)}{!segments.length&&<Empty compact icon={FileAudio} title="Waiting for the words" text="Your transcript will appear after a conversation or successful transcription."/>}</section>}
    {edit&&<SegmentEditor segment={edit} onClose={()=>setEdit(null)} onSaved={()=>void fetchDetail()}/>}
  </>;
}

function SegmentEditor({segment,onClose,onSaved}:{segment:Segment;onClose:()=>void;onSaved:()=>void}){
  const {notify}=useApp();const [form,setForm]=useState({text:segment.text,role:segment.role,start:segment.start,end:segment.end}),[busy,setBusy]=useState(false);
  const save=async(e:FormEvent)=>{e.preventDefault();if(form.end<form.start){notify('End time must be after the start time.',true);return;}setBusy(true);try{await patch(`/segments/${segment.id}`,form);notify('Transcript corrected. Create a fresh review to update feedback.');onSaved();onClose();}catch(error){notify(errorMessage(error),true);}finally{setBusy(false);}};
  return <Modal title="Correct transcript" onClose={onClose}><form className="form-stack" onSubmit={e=>void save(e)}><Field label="Speaker role"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Segment['role']})}>{['candidate','interviewer','unknown','other'].map(role=><option key={role} value={role}>{label(role)}</option>)}</select></Field><Field label="What was said"><textarea autoFocus required rows={7} value={form.text} onChange={e=>setForm({...form,text:e.target.value})}/></Field><div className="form-row"><Field label="Start · seconds"><input type="number" min="0" step="0.1" value={form.start} onChange={e=>setForm({...form,start:Number(e.target.value)})}/></Field><Field label="End · seconds"><input type="number" min={form.start} step="0.1" value={form.end} onChange={e=>setForm({...form,end:Number(e.target.value)})}/></Field></div><div className="modal-footer"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" busy={busy}>Save correction</Button></div></form></Modal>;
}

function ImportModal({onClose}:{onClose:()=>void}){
  const {data,selectedJob,setSelectedSession,refresh,notify}=useApp();
  const [job,setJob]=useState(selectedJob||data.jobs[0]?.id||''),[title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!file)return;setBusy(true);try{const body=new FormData();body.append('file',file);body.append('job_id',job);body.append('title',title||file.name);const result=await api<{session:Session}>('/imports',{method:'POST',body});setSelectedSession(result.session.id);await refresh();notify('Recording saved. Transcription and speaker separation are processing in the background.');onClose();}catch(error){notify(errorMessage(error),true);}finally{setBusy(false);}};
  return <Modal title="Bring a conversation into focus" subtitle="Import a recording to transcribe, identify speakers, and review your answers locally." onClose={onClose}><form className="form-stack" onSubmit={e=>void submit(e)}><Field label="Related opportunity"><select required value={job} onChange={e=>setJob(e.target.value)}><option value="" disabled>Select opportunity</option>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></Field>{!data.jobs.length&&<p className="notice">Add an opportunity in Jobs first so Helios has the right context for feedback.</p>}<Field label="Session title"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Product interview · first round"/></Field><label className="upload-zone"><Upload size={26}/><strong>{file?file.name:'Choose an audio or video recording'}</strong><span>MP3, WAV, M4A, WebM, MP4 and other common formats</span><input type="file" required accept="audio/*,video/*,.mkv,.flac,.ogg" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><p className="field-hint">Only import recordings you are allowed to use. Speaker separation may require a one-time model setup in Settings.</p><div className="modal-footer"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" busy={busy} disabled={!file||!job}><Upload size={15}/>Import recording</Button></div></form></Modal>;
}
